#!/bin/bash

usage(){
    U1="usage: $0 [-setcookie <cookie>] [-nocookie] "
    U2="[-nettick <tick>] [-vsn <OTP version>]"
    echo $U1 $U2
    exit
}

deps="eper"
. `dirname $0`/paths

VSN=""
XTRA=""

while [ -n "$1" ] 
  do
  case $1 in
      "-help"|"-h"|"-?")
	  usage
	  ;;
      "-vsn"|"-version")
	  VSN="+R "$2
	  shift
	  ;;
      "-nettick"|"-tick")
	  nettick="-kernel net_ticktime $2"
	  shift 
	  ;;
      "-cookie"|"-setcookie")
	  cookie="-setcookie $2"
	  shift
	  ;;
      "-nocookie")
	  cookie=""
	  ;;
      "-*")
          echo unrecognized flag $1
	  usage
          ;;
      *)
          XTRA=" $XTRA $1"
          ;;
  esac
  shift
done

name="redbug_"$$ 
DISTR="-noshell -hidden -sname $name $cookie $nettick"
START="-run redbug start"

erl $VSN $DISTR $PATHS $START $XTRA
